apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-sample-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ayu9x/GitOps-Project.git'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
